### ISSUE TITLE
innamebeforetitle=true not working for @inbook?

### ISSUE THREAD

**Issue by hcf-n** [moewew/biblatex-ext#20] opened 2020-10-07 20:03 UTC
**Describe the bug**
I have trouble getting innamebeforetitle=true to function as expected for @inbook

**To Reproduce**
```
\documentclass[preview,border=10pt]{standalone} %
\usepackage[backend=biber,style=ext-authoryear,innamebeforetitle=true]{biblatex} %
\usepackage{filecontents} %

\addbibresource{example.bib} %

\begin{filecontents}{example.bib}
@inbook{lewis16,
author =       {Lewis, David},
title =        {The Paradoxes of Time Travel},
booktitle =    {Science Fiction and Philosophy},
year =         {2016},
crossref =     {schneider16},
pages =        {357--369}
}

@Book{schneider16,
title =        {Science Fiction and Philosophy},
year =         {2016},
editor =       {Schneider, Susan},
publisher =    {Wiley},
location =     {New York}
}

\end{filecontents}

\DeclareFieldFormat[incollection]{pages}{#1} %
\renewcommand*{\intitlepunct}{\space} %

\begin{document}

\nocite{lewis16}

\printbibliography
\end{document}

```
The MWE works as expected with @incollection instead of @inbook

**Comment by moewew** [comment] 2020-10-08 06:15
Thank you for reporting this.

I'd say this is sort of by design. An `@inbook` entry is supposed to be 'in a `@book`' and a `@book` would normally have an author (which would be the `@inbook`'s `bookauthor`) and that's who we would see before the title. But there is no `bookauthor` in this example.

You mention that `@incollection` solves the issue and I would claim that this is the correct entry type to model this anyway.
```latex
\documentclass{article}
\usepackage[backend=biber,style=ext-authoryear,innamebeforetitle=true]{biblatex}

\DeclareFieldFormat[incollection]{pages}{#1}
\renewcommand*{\intitlepunct}{\space}

\begin{filecontents}{\jobname.bib}
@incollection{lewis16,
  author    = {Lewis, David},
  title     = {The Paradoxes of Time Travel},
  crossref  = {schneider16},
  pages     = {357--369},
}
@collection{schneider16,
  title     = {Science Fiction and Philosophy},
  year      = {2016},
  editor    = {Schneider, Susan},
  publisher = {Wiley},
  location  = {New York},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\nocite{lewis16}

\printbibliography
\end{document}
```

I'm not sure if there is a legitimate use of `@inbook` where you'd want this to work differently, so if there are any examples of entries that should not have been `@incollection`s yet still have this issue, I'd love to see them.

**Comment by hcf-n** [comment] 2020-10-08 09:57
I see. Thank you for clearing that up for me.

**Comment by moewew** [comment] 2020-10-08 15:46
OK then, I'll close this if that's alright with you.

If there are examples of entries that are clearly `@inbook`s where the current behaviour is wrong, please don't hesitate to add them here and we can reopen this issue.

**Closed as completed by moewew** 2020-10-08 15:46 UTC
Labels: works as intended
